input {


  kafka {
      bootstrap_servers => ["localhost:9092"]
      topics => ["tweets_ukr"]
  }

}

output {
  elasticsearch { 
    hosts => ["localhost:9200"]
    index => "tweets_ukr"
   }
  stdout { codec => rubydebug }
}
